apiVersion: apps/v1
kind: Deployment
metadata:
    name: flpmarcos-deployment
    labels:
        app: flpmarcos
        type: front-end
spec:
    template: 
        metadata:
            name: flpmarcos-pod
            labels: 
                app: flpmarcos
                type: front-end
        spec:
            containers:
            - name: nginx-container
              image: nginx
    replicas: 3
    selector:
        matchLabels:
            type: front-end